/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chickengoaway;

/**
 *
 * @author huy.vu
 */
public class form_order extends javax.swing.JFrame {

    /**
     * Creates new form form_order
     */
    public form_order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_header = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        lbl_phoneNumber = new javax.swing.JLabel();
        lbl_timedeli = new javax.swing.JLabel();
        lbl_shipFee = new javax.swing.JLabel();
        txt_Address = new javax.swing.JTextField();
        txt_numberPhone = new javax.swing.JTextField();
        txt_timeDeliverli = new javax.swing.JTextField();
        txt_shipFee = new javax.swing.JTextField();
        btn_selectFoods = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_orderDetails = new javax.swing.JTable();
        btn_OK = new javax.swing.JButton();
        btn_calcel = new javax.swing.JButton();
        lbl_total = new javax.swing.JLabel();
        lbl_totalFee = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_header.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_header.setText("THÊM ĐƠN HÀNG");

        lbl_address.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_address.setText("Địa chỉ giao hàng:");

        lbl_phoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_phoneNumber.setText("Số điện thoại :");

        lbl_timedeli.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_timedeli.setText("Thời gian giao");

        lbl_shipFee.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_shipFee.setText("Phí ship:");

        txt_Address.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AddressActionPerformed(evt);
            }
        });

        txt_numberPhone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_numberPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numberPhoneActionPerformed(evt);
            }
        });

        txt_timeDeliverli.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_timeDeliverli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timeDeliverliActionPerformed(evt);
            }
        });

        txt_shipFee.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btn_selectFoods.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_selectFoods.setText("Chọn món");
        btn_selectFoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectFoodsActionPerformed(evt);
            }
        });

        tbl_orderDetails.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tbl_orderDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Món Ăn", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_orderDetails);
        if (tbl_orderDetails.getColumnModel().getColumnCount() > 0) {
            tbl_orderDetails.getColumnModel().getColumn(0).setResizable(false);
            tbl_orderDetails.getColumnModel().getColumn(1).setResizable(false);
            tbl_orderDetails.getColumnModel().getColumn(2).setResizable(false);
            tbl_orderDetails.getColumnModel().getColumn(3).setResizable(false);
            tbl_orderDetails.getColumnModel().getColumn(4).setResizable(false);
        }

        btn_OK.setBackground(new java.awt.Color(0, 204, 102));
        btn_OK.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_OK.setText("Đồng ý");
        btn_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OKActionPerformed(evt);
            }
        });

        btn_calcel.setBackground(new java.awt.Color(255, 0, 0));
        btn_calcel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_calcel.setText("Hủy");
        btn_calcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcelActionPerformed(evt);
            }
        });

        lbl_total.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_total.setText("Tổng cộng");

        lbl_totalFee.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_totalFee.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btn_OK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_calcel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(326, 326, 326)
                                .addComponent(lbl_total)
                                .addGap(46, 46, 46)
                                .addComponent(lbl_totalFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_selectFoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(34, 34, 34)
                                .addComponent(lbl_shipFee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_shipFee, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(240, 240, 240)))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_address)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Address))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addComponent(lbl_header))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_phoneNumber)
                                .addGap(43, 43, 43)
                                .addComponent(txt_numberPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(lbl_timedeli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_timeDeliverli, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_header)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbl_address))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_numberPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_phoneNumber)
                        .addComponent(lbl_timedeli)
                        .addComponent(txt_timeDeliverli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_selectFoods)
                            .addComponent(lbl_shipFee))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_shipFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_total)
                    .addComponent(lbl_totalFee, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calcel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AddressActionPerformed

    private void btn_selectFoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectFoodsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_selectFoodsActionPerformed

    private void txt_numberPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numberPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numberPhoneActionPerformed

    private void txt_timeDeliverliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timeDeliverliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timeDeliverliActionPerformed

    private void btn_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_OKActionPerformed

    private void btn_calcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_calcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_OK;
    private javax.swing.JButton btn_calcel;
    private javax.swing.JButton btn_selectFoods;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_header;
    private javax.swing.JLabel lbl_phoneNumber;
    private javax.swing.JLabel lbl_shipFee;
    private javax.swing.JLabel lbl_timedeli;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_totalFee;
    private javax.swing.JTable tbl_orderDetails;
    private javax.swing.JTextField txt_Address;
    private javax.swing.JTextField txt_numberPhone;
    private javax.swing.JTextField txt_shipFee;
    private javax.swing.JTextField txt_timeDeliverli;
    // End of variables declaration//GEN-END:variables
}
