/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chickengoaway;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huy.vu
 */
public class form_print extends javax.swing.JFrame {

    /**
     * Creates new form print
     */
    public form_print() {
        initComponents();
    }
    private String orderIdentify = "";
    
    /**
     * SELECT  TOP 1 * FORM order where OrderID = orderID
     * SELECT OrderDetails.orderId, OrderDetails.Count, foods.Name, foods.Prices FROM foods INNER JOIN OrderDetails ON foods.[ID] = OrderDetails.[foods] 
     * WHERE (((OrderDetails.orderId)=18040801));

     * 
     * @param orderID 
     */
    public form_print(String orderID) {
        this.orderIdentify = orderID;
        initComponents();
        
        DefaultTableModel tableDetails = (DefaultTableModel) tbl_billDetails.getModel();
        
        
        //Select data
        String strQuerryCustomer = "SELECT * FROM [order] WHERE (((order.OrderID)=" + orderID + "));" ;
        String strQuerryFood = "SELECT OrderDetails.orderId, OrderDetails.Count, foods.Name, foods.Prices "
                + "FROM foods INNER JOIN OrderDetails ON foods.[ID] = OrderDetails.[foods] "
                + "WHERE (((OrderDetails.orderId)=" + orderID + "));";
        
        ResultSet customerInfo = ChickenGoAway._helpper.executeQuerry(strQuerryCustomer);
        ResultSet orderInfo = ChickenGoAway._helpper.executeQuerry(strQuerryFood);
        int total,fee;
        try {
            while (customerInfo.next()){
                
                total = Integer.valueOf(customerInfo.getString("Ship")) + Integer.valueOf(customerInfo.getString("Fee")) ;
                fee = Integer.valueOf(customerInfo.getString("Ship"));
                lbl_tobeUpdate_Address.setText(customerInfo.getString("Address"));
                lbl_tobeUpdate_phoneNumber.setText(customerInfo.getString("PhoneNumber"));
                lbl_tobeUpdate_shipFee.setText(String.format("%,d", fee));
                lbl_tobeUpdate_time.setText(customerInfo.getString("timeDelivery"));
                
                
                lbl_tobeUpdate_total.setText(String.format("%,d", total));   
            }
            String foodName, quantity, price;
            int foodFee;
            while (orderInfo.next()){
                
                foodName = orderInfo.getString("Name");
                quantity = orderInfo.getString("Count");
                price = orderInfo.getString("Prices");
                foodFee = Integer.valueOf(quantity) * Integer.valueOf(price);
                tableDetails.addRow(new Object[]{foodName, quantity, price, String.format("%,d", foodFee)});
            }
            
            /**
             * DefaultTableModel model = (DefaultTableModel) table.getModel();
             * model.addRow(new Object[]{"Column 1", "Column 2", "Column 3"});
             */
        
        
        } catch (SQLException ex) {
            Logger.getLogger(form_print.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel_print = new javax.swing.JPanel();
        img_logo = new javax.swing.JLabel();
        lbl_webAddress1 = new javax.swing.JLabel();
        lbl_webAddress2 = new javax.swing.JLabel();
        lbl_webAddress3 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_intruction = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        lbl_address2 = new javax.swing.JLabel();
        lbl_address1 = new javax.swing.JLabel();
        lbl_formName = new javax.swing.JLabel();
        lbl_customerAddress = new javax.swing.JLabel();
        lbl_tobeUpdate_Address = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        lbl_tobeUpdate_time = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_billDetails = new javax.swing.JTable();
        lbl_shipFee = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_tobeUpdate_shipFee = new javax.swing.JLabel();
        lbl_tobeUpdate_total = new javax.swing.JLabel();
        lbl_phoneNumber = new javax.swing.JLabel();
        lbl_tobeUpdate_phoneNumber = new javax.swing.JLabel();
        btn_print = new javax.swing.JToggleButton();
        btn_cancel = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(950, 700));

        Jpanel_print.setBackground(new java.awt.Color(255, 255, 255));
        Jpanel_print.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Jpanel_print.setMaximumSize(new java.awt.Dimension(0, 0));

        img_logo.setIcon(new javax.swing.ImageIcon("D:\\workSpace\\javadev\\git\\design\\logo.jpg")); // NOI18N

        lbl_webAddress1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_webAddress1.setText("www.gakhongloithoat.com");

        lbl_webAddress2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_webAddress2.setText("www.gakhongloithoat.vn");

        lbl_webAddress3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_webAddress3.setText("www.gakhongloithoat.com.vn");

        lbl_name.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_name.setText("GÀ KHÔNG LỐI THOÁT");

        lbl_intruction.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_intruction.setText("CHÚNG TÔI TỰ HÀO LÀ NGƯỜI SÁNG LẬP VÀ ĐẶT TÊN");

        lbl_address.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_address.setText("Địa chỉ:");

        lbl_address2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_address2.setText("Cơ sở 2: 71 Ái Mộ, Phường Bồ Đề, Quận Long Biên - Hotline: 0968 520 056");

        lbl_address1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_address1.setText("Cơ sở 1: 315 Quan Hoa - Cầu Giấy - Hà Nội - Hotline: 0963 466 000");

        lbl_formName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_formName.setText("HÓA ĐƠN BÁN HÀNG");

        lbl_customerAddress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_customerAddress.setText("Địa chỉ giao hàng:");

        lbl_tobeUpdate_Address.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_tobeUpdate_Address.setText("___");

        lbl_time.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_time.setText("Thời gian giao hàng: ");

        lbl_tobeUpdate_time.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_tobeUpdate_time.setText("_____");

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 204));
        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        tbl_billDetails.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tbl_billDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên món ăn", "Giá", "Số Lượng", "Thành Tiền"
            }
        ));
        tbl_billDetails.setRowHeight(24);
        jScrollPane1.setViewportView(tbl_billDetails);
        if (tbl_billDetails.getColumnModel().getColumnCount() > 0) {
            tbl_billDetails.getColumnModel().getColumn(0).setResizable(false);
            tbl_billDetails.getColumnModel().getColumn(0).setPreferredWidth(500);
            tbl_billDetails.getColumnModel().getColumn(1).setResizable(false);
            tbl_billDetails.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbl_billDetails.getColumnModel().getColumn(2).setResizable(false);
            tbl_billDetails.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbl_billDetails.getColumnModel().getColumn(3).setResizable(false);
            tbl_billDetails.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        lbl_shipFee.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_shipFee.setText("Phí ship:");

        lbl_total.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_total.setText("Tổng cộng");

        lbl_tobeUpdate_shipFee.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_tobeUpdate_shipFee.setText("0");

        lbl_tobeUpdate_total.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_tobeUpdate_total.setText("0");

        lbl_phoneNumber.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_phoneNumber.setText("Điện thoại:");

        lbl_tobeUpdate_phoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbl_tobeUpdate_phoneNumber.setText("_____");

        javax.swing.GroupLayout Jpanel_printLayout = new javax.swing.GroupLayout(Jpanel_print);
        Jpanel_print.setLayout(Jpanel_printLayout);
        Jpanel_printLayout.setHorizontalGroup(
            Jpanel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_printLayout.createSequentialGroup()
                .addGroup(Jpanel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_printLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(img_logo)
                        .addGroup(Jpanel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Jpanel_printLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(lbl_webAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_webAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Jpanel_printLayout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(lbl_formName))
                            .addGroup(Jpanel_printLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(lbl_webAddress3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Jpanel_printLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(lbl_intruction, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Jpanel_printLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Jpanel_printLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Jpanel_printLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(Jpanel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_address2)
                                    .addComponent(lbl_address1)))))
                    .addGroup(Jpanel_printLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(Jpanel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_customerAddress)
                            .addComponent(lbl_time))
                        .addGap(15, 15, 15)
                        .addGroup(Jpanel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tobeUpdate_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Jpanel_printLayout.createSequentialGroup()
                                .addComponent(lbl_tobeUpdate_time)
                                .addGap(274, 274, 274)
                                .addComponent(lbl_phoneNumber)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_tobeUpdate_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Jpanel_printLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_printLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Jpanel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_shipFee)
                    .addComponent(lbl_total))
                .addGap(29, 29, 29)
                .addGroup(Jpanel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tobeUpdate_total)
                    .addComponent(lbl_tobeUpdate_shipFee))
                .addGap(125, 125, 125))
        );
        Jpanel_printLayout.setVerticalGroup(
            Jpanel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_printLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Jpanel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_printLayout.createSequentialGroup()
                        .addGroup(Jpanel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_webAddress1)
                            .addComponent(lbl_webAddress2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_webAddress3)
                        .addGap(13, 13, 13)
                        .addComponent(lbl_intruction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_address)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_address1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_address2)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_formName))
                    .addComponent(img_logo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Jpanel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_customerAddress)
                    .addComponent(lbl_tobeUpdate_Address))
                .addGap(18, 18, 18)
                .addGroup(Jpanel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_time)
                    .addComponent(lbl_tobeUpdate_time)
                    .addComponent(lbl_phoneNumber)
                    .addComponent(lbl_tobeUpdate_phoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(Jpanel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_shipFee)
                    .addComponent(lbl_tobeUpdate_shipFee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Jpanel_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_total)
                    .addComponent(lbl_tobeUpdate_total))
                .addGap(27, 27, 27))
        );

        btn_print.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_print.setText("In");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_cancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_cancel.setText("Hủy");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(btn_print)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancel)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Jpanel_print, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Jpanel_print, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_print)
                    .addComponent(btn_cancel))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        
        PrinterJob printJob = PrinterJob.getPrinterJob();
        printJob.setJobName("Print bill: " + this.orderIdentify);
        
        printJob.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                pf.setOrientation(PageFormat.PORTRAIT);
                 if(pageNum>0){
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.63,0.68);
                Jpanel_print.paint(g2);
                return Printable.PAGE_EXISTS;
            }
        });
        
        boolean ok = printJob.printDialog();
        if(ok){
        try{
            
        printJob.print();
        }
        catch (PrinterException ex){}
        }
            
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed

         // confirm that close without save and close form 
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int intResut = JOptionPane.showConfirmDialog (null, "Bạn có muốn hủy đóng?","Warning",dialogButton);
        if(intResut == JOptionPane.YES_OPTION){
            this.dispose();       
        }
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel_print;
    private javax.swing.JToggleButton btn_cancel;
    private javax.swing.JToggleButton btn_print;
    private javax.swing.JLabel img_logo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_address1;
    private javax.swing.JLabel lbl_address2;
    private javax.swing.JLabel lbl_customerAddress;
    private javax.swing.JLabel lbl_formName;
    private javax.swing.JLabel lbl_intruction;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_phoneNumber;
    private javax.swing.JLabel lbl_shipFee;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_tobeUpdate_Address;
    private javax.swing.JLabel lbl_tobeUpdate_phoneNumber;
    private javax.swing.JLabel lbl_tobeUpdate_shipFee;
    private javax.swing.JLabel lbl_tobeUpdate_time;
    private javax.swing.JLabel lbl_tobeUpdate_total;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_webAddress1;
    private javax.swing.JLabel lbl_webAddress2;
    private javax.swing.JLabel lbl_webAddress3;
    private javax.swing.JTable tbl_billDetails;
    // End of variables declaration//GEN-END:variables
}
